export const monthlyEvents = [
  {
    id: 1,
    name: "January",
    image: "/assets/projects/1.jpg",
    bgImage: "/assets/backgrounds/blanket.jpg",
    frameworks: [{ id: 1, name: "오이도로 첫 여행을 갔던 1월" }],
  },
  {
    id: 2,
    name: "February",
    image: "/assets/projects/2.jpg",
    bgImage: "/assets/backgrounds/curtains.jpg",
    frameworks: [{ id: 1, name: "디핀에서 맛있는 식사를 즐겼던 2월" }],
  },
  {
    id: 3,
    name: "March",
    image: "/assets/projects/3.jpg",
    bgImage: "/assets/backgrounds/map.jpg",
    frameworks: [{ id: 1, name: "연남동에서 첫커플링을 맞췄던 3월" }],
  },
  {
    id: 4,
    name: "April",
    image: "/assets/projects/4.jpg",
    bgImage: "/assets/backgrounds/poster.jpg",
    frameworks: [{ id: 1, name: "벚꽃을 보고 호두와 산책을 했던 4월" }],
  },
  {
    id: 5,
    name: "May",
    image: "/assets/projects/5.jpg",
    bgImage: "/assets/backgrounds/table.jpg",
    frameworks: [{ id: 1, name: "호치민 여행과 행궁동을 즐겼던 5월" }],
  },
  {
    id: 6,
    name: "June",
    image: "/assets/projects/6.jpg",
    bgImage: "/assets/backgrounds/curtains.jpg",
    frameworks: [{ id: 2, name: "에다마메에서 맛있는 식사를 즐겼던 6월" }],
  },
  {
    id: 7,
    name: "July",
    image: "/assets/projects/7.jpg",
    bgImage: "/assets/backgrounds/curtains.jpg",
    frameworks: [{ id: 1, name: "조광201과 유치회관을 다녀왔던 7월" }],
  },
  {
    id: 8,
    name: "August",
    image: "/assets/projects/8.jpg",
    bgImage: "/assets/backgrounds/curtains.jpg",
    frameworks: [{ id: 1, name: "솔이의 생일을 축하하는 8월" }],
  },
];
